<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'QFGW' => 1,
        'QWMB' => 2,
        'QHBJ' => 3,
        'QWZFW' => 4,
        'QRMFY' => 5,
        'QJCY' => 6,
        'QGAJ' => 7,
        'QCZJ' => 8,
        'QGXW' => 9,
        'QJYJ' => 10,
        'QSFJ' => 11,
        'QRSJ' => 12,
        'QZJJ' => 13,
        'XRSJ' => 14,
        'QGBDST' => 15,
        'QSLJ' => 16,
        'QLYJ' => 17,
        'QJTYSJ' => 18,
        'QLFW' => 19,
        'QFGJ' => 20,
        'QSWJ' => 21,
        'QMZJ' => 22,
        'QNYJ' => 23,
        'QWGXJ' => 24,
        'QZRZYGHJ' => 25,
        'QWJW' => 26,
        'QSHUIWJ' => 27,
        'QJJD' => 28,
        'QTJJ' => 29,
        'QSCJDJ' => 30,
        'QAJJ' => 31,
        'QZFJRB' => 32,
        'QGGZWGLJ' => 33,
        'QXXZX' => 34,
        'QWWXB' => 35,
        'QBWB' => 36,
        'QKJJ' => 37,
        'QSJJ' => 38,
        'QLSJ' => 39,
        'QCQGZFJ' => 40,
        'QDAJ' => 41,
        'QZGH' => 42,
        'QTW' => 43,
        'QGDGS' => 44,
        'QDXGS' => 45,
        'QYDGS' => 46,
        'QLTGS' => 47,
    );
}
