<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['QFGW'] => 'QFGW',
        IUserGroup::ID['QWMB'] => 'QWMB',
        IUserGroup::ID['QHBJ'] => 'QHBJ',
        IUserGroup::ID['QWZFW'] => 'QWZFW',
        IUserGroup::ID['QRMFY'] => 'QRMFY',
        IUserGroup::ID['QJCY'] => 'QJCY',
        IUserGroup::ID['QGAJ'] => 'QGAJ',
        IUserGroup::ID['QCZJ'] => 'QCZJ',
        IUserGroup::ID['QGXW'] => 'QGXW',
        IUserGroup::ID['QJYJ'] => 'QJYJ',
        IUserGroup::ID['QSFJ'] => 'QSFJ',
        IUserGroup::ID['QRSJ'] => 'QRSJ',
        IUserGroup::ID['QZJJ'] => 'QZJJ',
        IUserGroup::ID['XRSJ'] => 'XRSJ',
        IUserGroup::ID['QGBDST'] => 'QGBDST',
        IUserGroup::ID['QSLJ'] => 'QSLJ',
        IUserGroup::ID['QLYJ'] => 'QLYJ',
        IUserGroup::ID['QJTYSJ'] => 'QJTYSJ',
        IUserGroup::ID['QLFW'] => 'QLFW',
        IUserGroup::ID['QFGJ'] => 'QFGJ',
        IUserGroup::ID['QSWJ'] => 'QSWJ',
        IUserGroup::ID['QMZJ'] => 'QMZJ',
        IUserGroup::ID['QNYJ'] => 'QNYJ',
        IUserGroup::ID['QWGXJ'] => 'QWGXJ',
        IUserGroup::ID['QZRZYGHJ'] => 'QZRZYGHJ',
        IUserGroup::ID['QWJW'] => 'QWJW',
        IUserGroup::ID['QSHUIWJ'] => 'QSHUIWJ',
        IUserGroup::ID['QJJD'] => 'QJJD',
        IUserGroup::ID['QTJJ'] => 'QTJJ',
        IUserGroup::ID['QSCJDJ'] => 'QSCJDJ',
        IUserGroup::ID['QAJJ'] => 'QAJJ',
        IUserGroup::ID['QZFJRB'] => 'QZFJRB',
        IUserGroup::ID['QGGZWGLJ'] => 'QGGZWGLJ',
        IUserGroup::ID['QXXZX'] => 'QXXZX',
        IUserGroup::ID['QWWXB'] => 'QWWXB',
        IUserGroup::ID['QBWB'] => 'QBWB',
        IUserGroup::ID['QKJJ'] => 'QKJJ',
        IUserGroup::ID['QSJJ'] => 'QSJJ',
        IUserGroup::ID['QLSJ'] => 'QLSJ',
        IUserGroup::ID['QCQGZFJ'] => 'QCQGZFJ',
        IUserGroup::ID['QDAJ'] => 'QDAJ',
        IUserGroup::ID['QZGH'] => 'QZGH',
        IUserGroup::ID['QTW'] => 'QTW',
        IUserGroup::ID['QGDGS'] => 'QGDGS',
        IUserGroup::ID['QDXGS'] => 'QDXGS',
        IUserGroup::ID['QYDGS'] => 'QYDGS',
        IUserGroup::ID['QLTGS'] => 'QLTGS',
    );
}
